services:
  db:
    image: postgres:15
    container_name: notifier-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifier
    ports:
      - "5432:5432"

  notifier-db:
    image: postgres:15
    container_name: notifier-notify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notifications"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  notifier:
    build:
      context: .
      dockerfile: Dockerfile.notifier
    container_name: notifier-svc
    environment:
      GRPC_PORT: "9090"
      DATABASE_URL: "postgres://postgres:postgres@notifier-db:5432/notifications?sslmode=disable"
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
    ports:
      - "9090:9090"
    depends_on:
      notifier-db:
        condition: service_healthy
      mailhog:
        condition: service_started