syntax = "proto3";

package notification.v1;

import "buf/validate/validate.proto";

option go_package = "github.com/Dashulya-coder/CaseTaskNotifier/gen/notification/v1;notificationv1";

service NotificationService {
  rpc ReserveConfirmation(ReserveConfirmationRequest) returns (ConfirmationResponse);
  rpc CommitConfirmation(CommitConfirmationRequest) returns (ConfirmationResponse);
  rpc CancelConfirmation(CancelConfirmationRequest) returns (ConfirmationResponse);

  rpc SendRelease(SendReleaseRequest) returns (SendResponse);
}

message ReserveConfirmationRequest {
  string saga_id = 1 [(buf.validate.field).string.uuid = true];
  string email = 2 [(buf.validate.field).string.email = true];
  string confirm_url = 3 [(buf.validate.field).string.uri = true];
}

message CommitConfirmationRequest {
  string saga_id = 1 [(buf.validate.field).string.uuid = true];
}

message CancelConfirmationRequest {
  string saga_id = 1 [(buf.validate.field).string.uuid = true];
}

message ConfirmationResponse {
  bool ok = 1;
}

message SendReleaseRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string repo_full_name = 2 [(buf.validate.field).string.min_len = 1];
  string tag = 3 [(buf.validate.field).string.min_len = 1];
  string release_url = 4 [(buf.validate.field).string.uri = true];
  string unsubscribe_url = 5 [(buf.validate.field).string.uri = true];
}

message SendResponse {
  bool delivered = 1;
}
